### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by Cablefish1** [atomic-junky/Project-Safe-House#1]
I'm getting a wierd missing dependencies error when trying to load the game.

The files it lists seems to be mostly there however nothing really opens in godot editor...

![image](https://github.com/atomic-junky/Project-Safe-House/assets/37123600/216ad7cb-88dd-4837-94f8-a2f1ebac4929)

**Comment by atomic-junky** [comment]
Ok, I think it's fixed

**Comment by Cablefish1** [comment]
> Ok, I think it's fixed

Yessir. I just tested it. It works now!
